#
#
---
- name: Provision dockerhosts, servers that host docker containers
  hosts: docker
  vars:
    centos_version: "7"
    tz: Europe/Amsterdam
    pv: sdb
    vg: vg01
    lv: data
    mp: "/container-data"  # MountPoint
    repo: docker-ce
  roles:
    - role: arikkert.nrpe_check_docker
      when: containers is defined
    - role: arikkert.postfix_nullclient

  # First (pre) configure the hosts
  # After that use roles to add special features
  pre_tasks:

    - name: Ensure target OS is supported
      ansible.builtin.fail:
        msg: "Playbook suitable/tested for CentOS {{ centos_version }}"
      when: ansible_distribution != 'CentOS' or ansible_distribution_major_version != centos_version

    #
    # docker itself
    #

    - name: Ensure docker-ce repo is installed
      ansible.builtin.shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/{{ repo }}.repo
      args:
        creates: /etc/yum.repos.d/{{ repo }}.repo

    - name: Ensure this repo is installed {{ repo }}
      ansible.builtin.yum:
        name: "{{ repo }}"

    - name: Ensure docker version is detected
      ansible.builtin.shell: docker --version
      register: docker_version
      changed_when: false
      check_mode: false

    - name: Ensure docker version is shown
      ansible.builtin.debug:
        msg: "{{ docker_version.stdout.split('\n') }}"

    - name: Ensure docker is running and enabled
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Ensure user docker is installed
      ansible.builtin.user:
        name: docker
        groups: docker
        append: true

    #
    # docker-compose
    #

    # not the old system docker-compose from redhat repo
    - name: Compose deps
      ansible.builtin.yum:
        name: docker-compose
        state: absent

    - name: Compose deps
      ansible.builtin.yum:
        name:
          - python2
          - python36

    # https://docs.docker.com/compose/install/#alternative-install-options
    - name: Ensure up2date downloaded version docker-compose is present
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-{{ ansible_system }}-{{ ansible_machine }}
        dest: /usr/local/bin/docker-compose
        backup: true
        mode: 0755

    - name: Ensure docker-compose version is detected
      ansible.builtin.shell: /usr/local/bin/docker-compose --version
      register: dockercompose_version
      changed_when: false
      check_mode: false

    - name: Ensure docker-compose versoin is shown
      ansible.builtin.debug:
        msg: "{{ dockercompose_version.stdout.split('\n') }}"

    #
    # continue
    #

    - name: Ensure .ssh dir exists
      ansible.builtin.file:
        path: /home/docker/.ssh
        state: directory
        mode: 0700
        owner: docker
        group: docker

    - name: Ensure key pair is created
      become: true
      become_user: docker
      community.crypto.openssh_keypair:
        path: "~/.ssh/id_rsa"
        owner: docker
        group: docker

    - name: Ensure dirs exist
      become: true
      become_user: docker
      ansible.builtin.file:
        path: /home/docker/{{ item }}
        state: directory
        mode: 0755
      loop:
        - docker
        - docker_compose

    - name: Ensure sudo is installed
      ansible.builtin.package:
        name: sudo

    - name: Ensure user docker can have elevated privileges
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/sudoers.d/
        mode: '0440'
        validate: visudo -cf %s
      loop:
        - 10_docker

    - name: Ensure VG exists
      ansible.builtin.lvg:
        pvs: /dev/{{ pv }}
        vg: "{{ vg }}"

    - name: Ensure LV exists
      ansible.builtin.lvol:
        vg: "{{ vg }}"
        lv: "{{ lv }}"
        size: 40G
        pvs: /dev/{{ pv }}

    - name: Ensure FS exists
      ansible.builtin.filesystem:
        fstype: xfs
        dev: /dev/mapper/{{ vg }}-{{ lv }}

    - name: Ensure MP (mountpoint) exists
      ansible.builtin.file:
        path: "{{ mp }}"
        state: directory
        mode: 0755

    - name: Mount
      ansible.builtin.mount:
        path: "{{ mp }}"
        src: /dev/mapper/{{ vg }}-{{ lv }}
        fstype: xfs
        state: mounted

    #
    # git
    #

    - name: Ensure git is installed
      ansible.builtin.yum:
        name: git

    - name: TZ {{ tz }}
      ansible.builtin.timezone:
        name: "{{ tz }}"

    #
    # helpers
    #

    - name: Ensure yamllint is installed
      ansible.builtin.yum:
        name: "{{ item }}"
      loop:
        - yamllint

    - name: Ensure hadolint is installed
      ansible.builtin.yum:
        name: "{{ item }}"
      loop:
        - https://harbottle.gitlab.io/harbottle-main/7/x86_64/harbottle-main-release.rpm
        - hadolint

    - name: Ensure version is detected
      ansible.builtin.shell: hadolint --version
      register: hadolint_version
      changed_when: false
      check_mode: false

    - name: Ensure hadolint version is shown
      ansible.builtin.debug:
        msg: "{{ hadolint_version.stdout.split('\n') }}"

    # sources op git clone https://github.com/fboender/multi-git-status.git
    # daarna patchen voor rhel7 ouwe git en locks
    - name: Ensure mgitstatus is installed
      ansible.builtin.copy:
        src: mgitstatus
        dest: /usr/local/bin/
        mode: 0755

    - name: Ensure mgitstatus manpage is installed
      ansible.builtin.copy:
        src: mgitstatus.1.gz
        dest: /usr/share/man/man1/
        mode: 0644

...
